#!/bin/bash


# matchId=$(rofi -dmenu -p "Enter Match Id")
function clear(){
    pkill -f 'iplscore.sh'
    echo "" > /tmp/display.txt
    pkill -RTMIN+10 i3blocks
}
match=$(cat ~/scripts/iplscore/livematches.txt | rofi -dmenu -i -p "Select Match")
echo $match
echo "STOP WATCHING"
if [[ $match == "STOP WATCHING" ]]
then
clear
exit 0
else
matchId=$(echo $match | awk '{print $4}')
echo $matchId
clear
$($HOME/scripts/iplscore/iplscore.sh $matchId)
# pkill -f 'ipl';
fi
